name: .NET

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - '**/README.md'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      if: success() && github.ref == 'refs/heads/main'
      with:
        PROJECT_FILE_PATH: src/DataTables/DataTables.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}